/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TagList = Array<string>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: InternationalizedArrayString;
  role?: InternationalizedArrayString;
  group?: "leadership" | "department";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: InternationalizedArrayText;
  tags?: InternationalizedArrayTagList;
  displayOrder?: number;
};

export type InternationalizedArrayTagList = Array<
  {
    _key: string;
  } & InternationalizedArrayTagListValue
>;

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type ProductCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productCategory";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  category?: ProductCategoryReference;
  spec?: InternationalizedArrayString;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  displayOrder?: number;
};

export type ProductCategory = {
  _id: string;
  _type: "productCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  slug?: Slug;
  summary?: InternationalizedArrayString;
  note?: InternationalizedArrayString;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  displayOrder?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InternationalizedArrayTagListValue = {
  _type: "internationalizedArrayTagListValue";
  value?: TagList;
  language?: string;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TagList
  | SanityImageAssetReference
  | TeamMember
  | InternationalizedArrayTagList
  | InternationalizedArrayText
  | SanityImageCrop
  | SanityImageHotspot
  | InternationalizedArrayString
  | ProductCategoryReference
  | Product
  | ProductCategory
  | Slug
  | InternationalizedArrayTagListValue
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/queries.ts
// Variable: PRODUCT_CATEGORIES_QUERY
// Query: *[_type == "productCategory"] | order(displayOrder asc) {    _id,    "slug": slug.current,      "title": coalesce(    title[language == $locale][0].value,    title[_key == $locale][0].value,    title[language == "en"][0].value,    title[_key == "en"][0].value  ),      "summary": coalesce(    summary[language == $locale][0].value,    summary[_key == $locale][0].value,    summary[language == "en"][0].value,    summary[_key == "en"][0].value  ),      "note": coalesce(    note[language == $locale][0].value,    note[_key == $locale][0].value,    note[language == "en"][0].value,    note[_key == "en"][0].value  ),      "image": image{    ...,    "alt": coalesce(alt, ""),    "lqip": asset->metadata.lqip  }  }
export type PRODUCT_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  title: string | null;
  summary: string | null;
  note: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | "";
    _type: "image";
    lqip: string | null;
  } | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[_type == "productCategory"] | order(displayOrder asc) {    _id,    "slug": slug.current,      "title": coalesce(    title[language == $locale][0].value,    title[_key == $locale][0].value,    title[language == "en"][0].value,    title[_key == "en"][0].value  ),      "summary": coalesce(    summary[language == $locale][0].value,    summary[_key == $locale][0].value,    summary[language == "en"][0].value,    summary[_key == "en"][0].value  ),      "note": coalesce(    note[language == $locale][0].value,    note[_key == $locale][0].value,    note[language == "en"][0].value,    note[_key == "en"][0].value  ),    "products": *[_type == "product" && category._ref == ^._id]      | order(displayOrder asc) {        _id,          "title": coalesce(    title[language == $locale][0].value,    title[_key == $locale][0].value,    title[language == "en"][0].value,    title[_key == "en"][0].value  ),          "spec": coalesce(    spec[language == $locale][0].value,    spec[_key == $locale][0].value,    spec[language == "en"][0].value,    spec[_key == "en"][0].value  ),          "image": image{    ...,    "alt": coalesce(alt, ""),    "lqip": asset->metadata.lqip  }      }  }
export type PRODUCTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  title: string | null;
  summary: string | null;
  note: string | null;
  products: Array<{
    _id: string;
    title: string | null;
    spec: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | "";
      _type: "image";
      lqip: string | null;
    } | null;
  }>;
}>;

// Source: ../src/sanity/queries.ts
// Variable: TEAM_QUERY
// Query: {    "leadership": *[_type == "teamMember" && group == "leadership"]      | order(displayOrder asc) {        _id,          "name": coalesce(    name[language == $locale][0].value,    name[_key == $locale][0].value,    name[language == "en"][0].value,    name[_key == "en"][0].value  ),          "role": coalesce(    role[language == $locale][0].value,    role[_key == $locale][0].value,    role[language == "en"][0].value,    role[_key == "en"][0].value  ),          "bio": coalesce(    bio[language == $locale][0].value,    bio[_key == $locale][0].value,    bio[language == "en"][0].value,    bio[_key == "en"][0].value  ),          "tags": coalesce(    tags[language == $locale][0].value,    tags[_key == $locale][0].value,    tags[language == "en"][0].value,    tags[_key == "en"][0].value  ),          "image": image{    ...,    "alt": coalesce(alt, ""),    "lqip": asset->metadata.lqip  }      },    "departments": *[_type == "teamMember" && group == "department"]      | order(displayOrder asc) {        _id,          "name": coalesce(    name[language == $locale][0].value,    name[_key == $locale][0].value,    name[language == "en"][0].value,    name[_key == "en"][0].value  ),          "role": coalesce(    role[language == $locale][0].value,    role[_key == $locale][0].value,    role[language == "en"][0].value,    role[_key == "en"][0].value  ),          "image": image{    ...,    "alt": coalesce(alt, ""),    "lqip": asset->metadata.lqip  }      }  }
export type TEAM_QUERY_RESULT = {
  leadership: Array<{
    _id: string;
    name: string | null;
    role: string | null;
    bio: string | null;
    tags: TagList | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | "";
      _type: "image";
      lqip: string | null;
    } | null;
  }>;
  departments: Array<{
    _id: string;
    name: string | null;
    role: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string | "";
      _type: "image";
      lqip: string | null;
    } | null;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "productCategory"] | order(displayOrder asc) {\n    _id,\n    "slug": slug.current,\n    \n  "title": coalesce(\n    title[language == $locale][0].value,\n    title[_key == $locale][0].value,\n    title[language == "en"][0].value,\n    title[_key == "en"][0].value\n  )\n,\n    \n  "summary": coalesce(\n    summary[language == $locale][0].value,\n    summary[_key == $locale][0].value,\n    summary[language == "en"][0].value,\n    summary[_key == "en"][0].value\n  )\n,\n    \n  "note": coalesce(\n    note[language == $locale][0].value,\n    note[_key == $locale][0].value,\n    note[language == "en"][0].value,\n    note[_key == "en"][0].value\n  )\n,\n    \n  "image": image{\n    ...,\n    "alt": coalesce(alt, ""),\n    "lqip": asset->metadata.lqip\n  }\n\n  }\n': PRODUCT_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "productCategory"] | order(displayOrder asc) {\n    _id,\n    "slug": slug.current,\n    \n  "title": coalesce(\n    title[language == $locale][0].value,\n    title[_key == $locale][0].value,\n    title[language == "en"][0].value,\n    title[_key == "en"][0].value\n  )\n,\n    \n  "summary": coalesce(\n    summary[language == $locale][0].value,\n    summary[_key == $locale][0].value,\n    summary[language == "en"][0].value,\n    summary[_key == "en"][0].value\n  )\n,\n    \n  "note": coalesce(\n    note[language == $locale][0].value,\n    note[_key == $locale][0].value,\n    note[language == "en"][0].value,\n    note[_key == "en"][0].value\n  )\n,\n    "products": *[_type == "product" && category._ref == ^._id]\n      | order(displayOrder asc) {\n        _id,\n        \n  "title": coalesce(\n    title[language == $locale][0].value,\n    title[_key == $locale][0].value,\n    title[language == "en"][0].value,\n    title[_key == "en"][0].value\n  )\n,\n        \n  "spec": coalesce(\n    spec[language == $locale][0].value,\n    spec[_key == $locale][0].value,\n    spec[language == "en"][0].value,\n    spec[_key == "en"][0].value\n  )\n,\n        \n  "image": image{\n    ...,\n    "alt": coalesce(alt, ""),\n    "lqip": asset->metadata.lqip\n  }\n\n      }\n  }\n': PRODUCTS_BY_CATEGORY_QUERY_RESULT;
    '\n  {\n    "leadership": *[_type == "teamMember" && group == "leadership"]\n      | order(displayOrder asc) {\n        _id,\n        \n  "name": coalesce(\n    name[language == $locale][0].value,\n    name[_key == $locale][0].value,\n    name[language == "en"][0].value,\n    name[_key == "en"][0].value\n  )\n,\n        \n  "role": coalesce(\n    role[language == $locale][0].value,\n    role[_key == $locale][0].value,\n    role[language == "en"][0].value,\n    role[_key == "en"][0].value\n  )\n,\n        \n  "bio": coalesce(\n    bio[language == $locale][0].value,\n    bio[_key == $locale][0].value,\n    bio[language == "en"][0].value,\n    bio[_key == "en"][0].value\n  )\n,\n        \n  "tags": coalesce(\n    tags[language == $locale][0].value,\n    tags[_key == $locale][0].value,\n    tags[language == "en"][0].value,\n    tags[_key == "en"][0].value\n  )\n,\n        \n  "image": image{\n    ...,\n    "alt": coalesce(alt, ""),\n    "lqip": asset->metadata.lqip\n  }\n\n      },\n    "departments": *[_type == "teamMember" && group == "department"]\n      | order(displayOrder asc) {\n        _id,\n        \n  "name": coalesce(\n    name[language == $locale][0].value,\n    name[_key == $locale][0].value,\n    name[language == "en"][0].value,\n    name[_key == "en"][0].value\n  )\n,\n        \n  "role": coalesce(\n    role[language == $locale][0].value,\n    role[_key == $locale][0].value,\n    role[language == "en"][0].value,\n    role[_key == "en"][0].value\n  )\n,\n        \n  "image": image{\n    ...,\n    "alt": coalesce(alt, ""),\n    "lqip": asset->metadata.lqip\n  }\n\n      }\n  }\n': TEAM_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
